live_config_reload = true

[colors.normal]
green = "#8ab5b5"

[cursor]
unfocused_hollow = false

[cursor.style]
blinking = "On"
shape = "Underline"

[env]
TERM = "alacritty"
WINIT_X11_SCALE_FACTOR = "1.0"

[font.normal]
family = "FiraCode Nerd Font"

[window]
decorations = "full"
dynamic_title = true
opacity = 1.0
startup_mode = "Windowed"

[window.dimensions]
columns = 82
lines = 25

[window.padding]
x = 30
y = 25
